package com.pallux.extractcore.core;

import com.pallux.extractcore.ExtractCore;
import com.pallux.extractcore.model.PlayerData;
import com.pallux.extractcore.util.ColorUtil;
import com.pallux.extractcore.util.ItemBuilder;
import com.pallux.extractcore.util.MessageUtil;
import org.bukkit.*;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.scheduler.BukkitRunnable;
import org.bukkit.scheduler.BukkitTask;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages all Core (Beacon) functionality.
 *
 * Scrap generated by the Core is now stored INSIDE the core (coreStoredScrap)
 * rather than going directly to the player's wallet. The player must open the
 * Core GUI and click "Collect" to transfer it to their balance.
 *
 * When an attacker destroys a core they receive a configurable % of the stored
 * scrap as a raid reward. The rest is lost. The core block is removed (not dropped).
 * The owner receives a fresh core item in their inventory with upgrades intact
 * (minus the configured % regression).
 */
public class CoreManager {

    private final ExtractCore plugin;
    private final NamespacedKey coreKey;

    private final Map<UUID, BukkitTask> generationTasks = new ConcurrentHashMap<>();
    private final Map<UUID, BukkitTask> pickupTasks     = new ConcurrentHashMap<>();
    private final Map<String, UUID>     coreLocs        = new ConcurrentHashMap<>();

    public CoreManager(ExtractCore plugin) {
        this.plugin  = plugin;
        this.coreKey = new NamespacedKey(plugin, plugin.getConfigManager()
                .getCoreConfig().getString("core.nbt-key", "extractcore_beacon"));
        Bukkit.getScheduler().runTaskLater(plugin, this::restoreAllCores, 40L);
    }

    // ── Core Item ─────────────────────────────────────────────────────────────

    public ItemStack createCoreItem() {
        FileConfiguration cfg = plugin.getConfigManager().getCoreConfig();
        return new ItemBuilder(Material.BEACON)
                .name(cfg.getString("core.item-name", "&#5B8DD9◈ &fExtract Core"))
                .lore(cfg.getStringList("core.item-lore"))
                .pdc(coreKey, "true")
                .hideAll()
                .build();
    }

    public boolean isCoreItem(ItemStack item) {
        if (item == null || !item.hasItemMeta()) return false;
        return item.getItemMeta().getPersistentDataContainer()
                .has(coreKey, PersistentDataType.STRING);
    }

    // ── Placement ─────────────────────────────────────────────────────────────

    public void placeCore(Player player, Location loc) {
        PlayerData data = plugin.getPlayerDataManager().get(player);
        if (data.isCorePlaced()) {
            MessageUtil.send(player, "core.already-placed");
            return;
        }
        data.setCorePlaced(true);
        data.setCoreWorld(loc.getWorld().getName());
        data.setCoreX(loc.getBlockX());
        data.setCoreY(loc.getBlockY());
        data.setCoreZ(loc.getBlockZ());

        coreLocs.put(locKey(loc), player.getUniqueId());
        plugin.getPlayerDataManager().saveAsync(data);
        startGeneration(player.getUniqueId());
        plugin.getHologramManager().spawnHologram(data);

        player.playSound(player.getLocation(), Sound.BLOCK_BEACON_ACTIVATE, 1f, 1f);
        MessageUtil.send(player, "core.core-placed");
    }

    // ── Collect Stored Scrap ──────────────────────────────────────────────────

    /**
     * Transfers all scrap stored inside the core to the player's balance.
     * Called when the player clicks the Collect button in CoreGUI.
     */
    public void collectStoredScrap(Player player) {
        PlayerData data = plugin.getPlayerDataManager().get(player);
        long stored = data.getCoreStoredScrap();
        if (stored <= 0) {
            String msg = plugin.getConfigManager().getMessages()
                    .getString("core.nothing-to-collect", "&7There is no Scrap stored in your Core yet.");
            player.sendMessage(ColorUtil.color(msg));
            return;
        }
        data.addScrap(stored);
        data.setCoreStoredScrap(0);
        plugin.getPlayerDataManager().saveAsync(data);

        player.playSound(player.getLocation(), Sound.ENTITY_EXPERIENCE_ORB_PICKUP, 1f, 1.2f);
        String msg = plugin.getConfigManager().getMessages()
                .getString("core.scrap-collected", "&#5B8DD9Collected &e+{amount} Scrap &7from your Core.")
                .replace("{amount}", ColorUtil.formatNumber(stored));
        player.sendMessage(ColorUtil.color(msg));
    }

    // ── Pickup ────────────────────────────────────────────────────────────────

    public void initiatePickup(Player player) {
        UUID uuid = player.getUniqueId();
        if (pickupTasks.containsKey(uuid)) return;

        int totalSeconds = plugin.getConfigManager().getCoreConfig()
                .getInt("core.pickup-duration-seconds", 10);

        player.playSound(player.getLocation(), Sound.BLOCK_PORTAL_TRIGGER, 0.5f, 1.5f);

        // Send the startup message with the total seconds already filled in
        MessageUtil.send(player, "core.core-pickup-started",
                "seconds", String.valueOf(totalSeconds));

        int[] remaining = { totalSeconds };

        BukkitTask task = new BukkitRunnable() {
            @Override public void run() {
                if (!player.isOnline()) { cancel(); pickupTasks.remove(uuid); return; }
                remaining[0]--;
                if (remaining[0] <= 0) {
                    finishPickup(player);
                    cancel();
                    pickupTasks.remove(uuid);
                } else {
                    MessageUtil.send(player, "core.core-pickup-progress",
                            "seconds", String.valueOf(remaining[0]));
                    player.playSound(player.getLocation(), Sound.BLOCK_NOTE_BLOCK_PLING, 0.5f,
                            0.5f + (0.05f * (totalSeconds - remaining[0])));
                }
            }
        }.runTaskTimer(plugin, 20L, 20L);
        pickupTasks.put(uuid, task);
    }

    public void cancelPickup(Player player) {
        BukkitTask task = pickupTasks.remove(player.getUniqueId());
        if (task != null) {
            task.cancel();
            MessageUtil.send(player, "core.core-pickup-cancelled");
        }
    }

    private void finishPickup(Player player) {
        PlayerData data = plugin.getPlayerDataManager().get(player);
        if (!data.isCorePlaced()) return;

        Location coreLoc = getCoreLocation(data);
        if (coreLoc != null && coreLoc.getBlock().getType() == Material.BEACON)
            coreLoc.getBlock().setType(Material.AIR);

        coreLocs.remove(locKey(data));
        stopGeneration(player.getUniqueId());
        plugin.getHologramManager().removeHologram(player.getUniqueId());

        // Auto-collect any stored scrap when picking up
        long stored = data.getCoreStoredScrap();
        if (stored > 0) {
            data.addScrap(stored);
            data.setCoreStoredScrap(0);
            String msg = plugin.getConfigManager().getMessages()
                    .getString("core.scrap-collected-on-pickup",
                            "&#5B8DD9Auto-collected &e{amount} Scrap &7stored in your Core.")
                    .replace("{amount}", ColorUtil.formatNumber(stored));
            player.sendMessage(ColorUtil.color(msg));
        }

        data.setCorePlaced(false);
        plugin.getPlayerDataManager().saveAsync(data);

        player.getInventory().addItem(createCoreItem());
        player.playSound(player.getLocation(), Sound.BLOCK_BEACON_DEACTIVATE, 1f, 1f);
        MessageUtil.send(player, "core.core-picked-up");
    }

    // ── Destroy (by other player) ─────────────────────────────────────────────

    /**
     * Called when an attacker successfully destroys another player's core.
     * - Core block is removed (does NOT drop as item)
     * - Attacker gets raid-reward-percent of stored scrap
     * - Rest of stored scrap is lost
     * - Owner receives a fresh core item (upgrades intact minus regression %)
     * - upgrade regression applied
     */
    public void destroyCore(Player owner, Player attacker) {
        PlayerData ownerData    = plugin.getPlayerDataManager().get(owner);
        PlayerData attackerData = plugin.getPlayerDataManager().get(attacker);
        FileConfiguration cfg  = plugin.getConfigManager().getCoreConfig();

        // Remove block (no drop)
        Location coreLoc = getCoreLocation(ownerData);
        if (coreLoc != null && coreLoc.getBlock().getType() == Material.BEACON)
            coreLoc.getBlock().setType(Material.AIR);

        coreLocs.remove(locKey(ownerData));
        stopGeneration(owner.getUniqueId());
        plugin.getHologramManager().removeHologram(owner.getUniqueId());

        // ── Raid reward from stored scrap ─────────────────────────────────
        long stored       = ownerData.getCoreStoredScrap();
        int  raidPct      = cfg.getInt("core.raid-reward-percent", 10);
        long raidReward   = stored * raidPct / 100;

        ownerData.setCoreStoredScrap(0);               // all stored scrap is gone
        if (raidReward > 0) attackerData.addScrap(raidReward);

        // ── Upgrade regression ────────────────────────────────────────────
        int lossPercent = cfg.getInt("core.destroy-loss-percent", 20);
        applyUpgradeLoss(ownerData, lossPercent);

        ownerData.setCorePlaced(false);
        plugin.getPlayerDataManager().saveAsync(ownerData);
        plugin.getPlayerDataManager().saveAsync(attackerData);

        // ── Owner notification ────────────────────────────────────────────
        // Give fresh core item (upgrades stored in PlayerData, not the item)
        owner.getInventory().addItem(createCoreItem());
        owner.playSound(owner.getLocation(), Sound.ENTITY_WITHER_DEATH, 0.5f, 0.8f);

        String ownerMsg = plugin.getConfigManager().getMessages()
                .getString("core.core-destroyed",
                        "&c&#FF4444Your Core was destroyed! &7You lost &e20%% &7of your upgrade progress.")
                .replace("{stored}", ColorUtil.formatNumber(stored));
        owner.sendMessage(ColorUtil.color(ownerMsg));

        // ── Attacker notification ─────────────────────────────────────────
        attacker.playSound(attacker.getLocation(), Sound.ENTITY_PLAYER_LEVELUP, 1f, 1.2f);
        String attackMsg = plugin.getConfigManager().getMessages()
                .getString("core.core-destroyed-attacker",
                        "&#5B8DD9You destroyed &e{player}'s &7Core!")
                .replace("{player}", owner.getName());
        attacker.sendMessage(ColorUtil.color(attackMsg));

        if (raidReward > 0) {
            String raidMsg = plugin.getConfigManager().getMessages()
                    .getString("core.raid-reward",
                            "&#FFD700⚔ Raid Reward: &e+{amount} Scrap &7from the Core's storage!")
                    .replace("{amount}", ColorUtil.formatNumber(raidReward))
                    .replace("{stored}", ColorUtil.formatNumber(stored));
            attacker.sendMessage(ColorUtil.color(raidMsg));
        }

        // ── Server broadcast ──────────────────────────────────────────────
        String broadcastMsg = plugin.getConfigManager().getMessages()
                .getString("core.core-raid-broadcast",
                        "&#FF4444⚔ &e{attacker} &7raided &e{owner}'s &7Core!")
                .replace("{attacker}", attacker.getName())
                .replace("{owner}", owner.getName());
        Bukkit.broadcast(net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
                .legacySection().deserialize(ColorUtil.color(broadcastMsg)));

        // ── XP + stats ────────────────────────────────────────────────────
        plugin.getLevelManager().addXp(attacker, "core-destroy");
        attackerData.incrementCoresDestroyed();
        plugin.getMilestoneManager().check(attacker, attackerData);
    }

    // ── Offline-owner destroy (called from CoreInteractListener) ─────────────

    public void destroyCoreOfflineOwner(UUID ownerUuid, Player attacker) {
        PlayerData ownerData    = plugin.getPlayerDataManager().get(ownerUuid);
        PlayerData attackerData = plugin.getPlayerDataManager().get(attacker);
        if (ownerData == null) return;

        plugin.getHologramManager().removeHologram(ownerUuid);
        FileConfiguration cfg = plugin.getConfigManager().getCoreConfig();
        long stored     = ownerData.getCoreStoredScrap();
        int  raidPct    = cfg.getInt("core.raid-reward-percent", 10);
        long raidReward = stored * raidPct / 100;

        ownerData.setCoreStoredScrap(0);
        if (raidReward > 0) attackerData.addScrap(raidReward);

        int lossPercent = cfg.getInt("core.destroy-loss-percent", 20);
        applyUpgradeLoss(ownerData, lossPercent);
        ownerData.setCorePlaced(false);

        plugin.getPlayerDataManager().saveAsync(ownerData);
        plugin.getPlayerDataManager().saveAsync(attackerData);

        attacker.playSound(attacker.getLocation(), Sound.ENTITY_PLAYER_LEVELUP, 1f, 1.2f);
        String msg = plugin.getConfigManager().getMessages()
                .getString("core.core-destroyed-attacker-offline",
                        "&#5B8DD9You destroyed &e{player}'s &7Core! &8(offline player)")
                .replace("{player}", ownerData.getName());
        attacker.sendMessage(ColorUtil.color(msg));

        if (raidReward > 0) {
            String raidMsg = plugin.getConfigManager().getMessages()
                    .getString("core.raid-reward",
                            "&#FFD700⚔ Raid Reward: &e+{amount} Scrap &7from the Core's storage!")
                    .replace("{amount}", ColorUtil.formatNumber(raidReward));
            attacker.sendMessage(ColorUtil.color(raidMsg));
        }

        // ── Server broadcast ──────────────────────────────────────────────
        String broadcastMsg = plugin.getConfigManager().getMessages()
                .getString("core.core-raid-broadcast",
                        "&#FF4444⚔ &e{attacker} &7raided &e{owner}'s &7Core!")
                .replace("{attacker}", attacker.getName())
                .replace("{owner}", ownerData.getName());
        Bukkit.broadcast(net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializer
                .legacySection().deserialize(ColorUtil.color(broadcastMsg)));

        plugin.getLevelManager().addXp(attacker, "core-destroy");
        attackerData.incrementCoresDestroyed();
        plugin.getMilestoneManager().check(attacker, attackerData);
        plugin.getPlayerDataManager().saveAsync(attackerData);
    }

    // ── Upgrade regression ────────────────────────────────────────────────────

    private void applyUpgradeLoss(PlayerData data, int percent) {
        int speedLevel = data.getCoreSpeedLevel();
        int prodLevel  = data.getCoreProductionLevel();
        data.setCoreSpeedLevel(Math.max(0, speedLevel - Math.max(1, speedLevel * percent / 100)));
        data.setCoreProductionLevel(Math.max(0, prodLevel - Math.max(1, prodLevel * percent / 100)));

        // Armory tiers also affected
        int[] tiers = {
                data.getSwordTier(), data.getPickaxeTier(), data.getAxeTier(),
                data.getHelmetTier(), data.getChestplateTier(), data.getLeggingsTier(), data.getBootsTier()
        };
        int[] r = new int[7];
        for (int i = 0; i < tiers.length; i++)
            r[i] = Math.max(1, tiers[i] - Math.max(1, tiers[i] * percent / 100));
        data.setSwordTier(r[0]); data.setPickaxeTier(r[1]); data.setAxeTier(r[2]);
        data.setHelmetTier(r[3]); data.setChestplateTier(r[4]);
        data.setLeggingsTier(r[5]); data.setBootsTier(r[6]);
    }

    // ── Generation Task ───────────────────────────────────────────────────────

    private void startGeneration(UUID uuid) {
        stopGeneration(uuid);
        long intervalTicks = getIntervalTicksForUUID(uuid);

        BukkitTask task = new BukkitRunnable() {
            @Override public void run() {
                Player player = Bukkit.getPlayer(uuid);
                if (player == null || !player.isOnline()) { cancel(); generationTasks.remove(uuid); return; }

                PlayerData data = plugin.getPlayerDataManager().get(uuid);
                if (!data.isCorePlaced()) { cancel(); generationTasks.remove(uuid); return; }

                long scrapAmount = getScrapPerInterval(data);

                // ── Store in core, NOT directly in wallet ─────────────────
                data.addCoreStoredScrap(scrapAmount);
                plugin.getPlayerDataManager().saveAsync(data);

                // Ambient particle
                Location coreLoc = getCoreLocation(data);
                if (coreLoc != null) {
                    coreLoc.getWorld().spawnParticle(Particle.PORTAL,
                            coreLoc.clone().add(0.5, 1, 0.5), 8, 0.2, 0.5, 0.2, 0.01);
                }
            }
        }.runTaskTimer(plugin, intervalTicks, intervalTicks);

        generationTasks.put(uuid, task);
    }

    private long getIntervalTicksForUUID(UUID uuid) {
        PlayerData data = plugin.getPlayerDataManager().get(uuid);
        if (data == null) return 200L;
        return getIntervalTicks(data) * 20L;
    }

    public long getIntervalTicks(PlayerData data) {
        FileConfiguration cfg = plugin.getConfigManager().getCoreConfig();
        int base = cfg.getInt("core.base-interval-seconds", 10);
        if (data == null) return base;
        int speedLevel = data.getCoreSpeedLevel();
        if (speedLevel > 0) {
            return cfg.getInt("core.upgrades.speed.levels." + speedLevel + ".interval-seconds", base);
        }
        return base;
    }

    public long getScrapPerInterval(PlayerData data) {
        FileConfiguration cfg = plugin.getConfigManager().getCoreConfig();
        long base = cfg.getLong("core.base-scrap-per-interval", 10);
        int prodLevel = data.getCoreProductionLevel();
        if (prodLevel > 0) {
            base = cfg.getLong("core.upgrades.production.levels." + prodLevel + ".scrap-per-interval", base);
        }
        return base;
    }

    private void stopGeneration(UUID uuid) {
        BukkitTask task = generationTasks.remove(uuid);
        if (task != null) task.cancel();
    }

    // ── Restore on startup ────────────────────────────────────────────────────

    private void restoreAllCores() {
        for (PlayerData data : plugin.getPlayerDataManager().getAll()) {
            if (data.isCorePlaced()) {
                coreLocs.put(locKey(data), data.getUuid());
                Player p = Bukkit.getPlayer(data.getUuid());
                if (p != null) {
                    startGeneration(data.getUuid());
                    plugin.getHologramManager().spawnHologram(data);
                }
            }
        }
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    public Location getCoreLocation(PlayerData data) {
        if (!data.isCorePlaced() || data.getCoreWorld() == null) return null;
        World world = Bukkit.getWorld(data.getCoreWorld());
        if (world == null) return null;
        return new Location(world, data.getCoreX(), data.getCoreY(), data.getCoreZ());
    }

    public UUID getOwnerAtLocation(Location loc) { return coreLocs.get(locKey(loc)); }

    private String locKey(Location loc) {
        return loc.getWorld().getName() + ":" + loc.getBlockX() + ":" + loc.getBlockY() + ":" + loc.getBlockZ();
    }
    private String locKey(PlayerData data) {
        return data.getCoreWorld() + ":" + data.getCoreX() + ":" + data.getCoreY() + ":" + data.getCoreZ();
    }

    public void shutdown() {
        generationTasks.values().forEach(BukkitTask::cancel);
        pickupTasks.values().forEach(BukkitTask::cancel);
        generationTasks.clear();
        pickupTasks.clear();
    }

    public boolean isPickingUp(UUID uuid) { return pickupTasks.containsKey(uuid); }
    public NamespacedKey getCoreKey()     { return coreKey; }
}